// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_coexp_fast
NumericVector cpp_coexp_fast(NumericMatrix ligand_expr, NumericMatrix receptor_expr);
RcppExport SEXP _SpaTalk_cpp_coexp_fast(SEXP ligand_exprSEXP, SEXP receptor_exprSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ligand_expr(ligand_exprSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type receptor_expr(receptor_exprSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_coexp_fast(ligand_expr, receptor_expr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_permutation_test
List cpp_permutation_test(NumericMatrix st_data_mat, IntegerVector ligand_genes, IntegerVector receptor_genes, IntegerVector sender_cells, IntegerVector receiver_cells, int per_num, int seed);
RcppExport SEXP _SpaTalk_cpp_permutation_test(SEXP st_data_matSEXP, SEXP ligand_genesSEXP, SEXP receptor_genesSEXP, SEXP sender_cellsSEXP, SEXP receiver_cellsSEXP, SEXP per_numSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type st_data_mat(st_data_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ligand_genes(ligand_genesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type receptor_genes(receptor_genesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sender_cells(sender_cellsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type receiver_cells(receiver_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type per_num(per_numSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_permutation_test(st_data_mat, ligand_genes, receptor_genes, sender_cells, receiver_cells, per_num, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_random_walk
NumericVector cpp_random_walk(CharacterVector ggi_src, CharacterVector ggi_dest, std::string receptor_name, CharacterVector tf_names, int n_walks, int max_hop, int seed);
RcppExport SEXP _SpaTalk_cpp_random_walk(SEXP ggi_srcSEXP, SEXP ggi_destSEXP, SEXP receptor_nameSEXP, SEXP tf_namesSEXP, SEXP n_walksSEXP, SEXP max_hopSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ggi_src(ggi_srcSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ggi_dest(ggi_destSEXP);
    Rcpp::traits::input_parameter< std::string >::type receptor_name(receptor_nameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type tf_names(tf_namesSEXP);
    Rcpp::traits::input_parameter< int >::type n_walks(n_walksSEXP);
    Rcpp::traits::input_parameter< int >::type max_hop(max_hopSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_random_walk(ggi_src, ggi_dest, receptor_name, tf_names, n_walks, max_hop, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fast_sampling
List cpp_fast_sampling(NumericVector spot_ndata, NumericMatrix sc_ndata_mat, List cell_indices_by_type, CharacterVector spot_celltypes, int iter_num, double tolerance, int seed);
RcppExport SEXP _SpaTalk_cpp_fast_sampling(SEXP spot_ndataSEXP, SEXP sc_ndata_matSEXP, SEXP cell_indices_by_typeSEXP, SEXP spot_celltypesSEXP, SEXP iter_numSEXP, SEXP toleranceSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type spot_ndata(spot_ndataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sc_ndata_mat(sc_ndata_matSEXP);
    Rcpp::traits::input_parameter< List >::type cell_indices_by_type(cell_indices_by_typeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type spot_celltypes(spot_celltypesSEXP);
    Rcpp::traits::input_parameter< int >::type iter_num(iter_numSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fast_sampling(spot_ndata, sc_ndata_mat, cell_indices_by_type, spot_celltypes, iter_num, tolerance, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_batch_coexp
NumericVector cpp_batch_coexp(NumericMatrix st_data_mat, IntegerVector src_genes, IntegerVector dest_genes, IntegerVector cell_indices);
RcppExport SEXP _SpaTalk_cpp_batch_coexp(SEXP st_data_matSEXP, SEXP src_genesSEXP, SEXP dest_genesSEXP, SEXP cell_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type st_data_mat(st_data_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_genes(src_genesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dest_genes(dest_genesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cell_indices(cell_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_batch_coexp(st_data_mat, src_genes, dest_genes, cell_indices));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fast_dist
NumericMatrix cpp_fast_dist(NumericVector x, NumericVector y);
RcppExport SEXP _SpaTalk_cpp_fast_dist(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fast_dist(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn
IntegerVector cpp_knn(NumericMatrix dist_mat, int query_idx, int k);
RcppExport SEXP _SpaTalk_cpp_knn(SEXP dist_matSEXP, SEXP query_idxSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type query_idx(query_idxSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn(dist_mat, query_idx, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_batch_cor
NumericVector cpp_batch_cor(NumericVector vec1, NumericMatrix mat);
RcppExport SEXP _SpaTalk_cpp_batch_cor(SEXP vec1SEXP, SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec1(vec1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_batch_cor(vec1, mat));
    return rcpp_result_gen;
END_RCPP
}
