# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast co-expression calculation (C++ vectorized)
#' @param ligand_expr Ligand expression matrix (n_genes x n_cells)
#' @param receptor_expr Receptor expression matrix (n_genes x n_cells)
#' @return Co-expression ratios
#' @export
cpp_coexp_fast <- function(ligand_expr, receptor_expr) {
    .Call('_SpaTalk_cpp_coexp_fast', PACKAGE = 'SpaTalk', ligand_expr, receptor_expr)
}

#' Fast permutation test - THE KEY OPTIMIZATION
#' @param st_data_mat Expression matrix
#' @param ligand_genes Ligand gene indices (1-based R indexing)
#' @param receptor_genes Receptor gene indices (1-based R indexing)
#' @param sender_cells Sender cell indices (1-based)
#' @param receiver_cells Receiver cell indices (1-based)
#' @param per_num Number of permutations
#' @param seed Random seed
#' @return List with real_ratio and pvalues
#' @export
cpp_permutation_test <- function(st_data_mat, ligand_genes, receptor_genes, sender_cells, receiver_cells, per_num = 1000L, seed = 123L) {
    .Call('_SpaTalk_cpp_permutation_test', PACKAGE = 'SpaTalk', st_data_mat, ligand_genes, receptor_genes, sender_cells, receiver_cells, per_num, seed)
}

#' Fast random walk for TF scoring
#' @param ggi_src Source gene names
#' @param ggi_dest Destination gene names  
#' @param receptor_name Starting receptor name
#' @param tf_names TF names to score
#' @param n_walks Number of walks
#' @param max_hop Maximum hops
#' @param seed Random seed
#' @return TF scores
#' @export
cpp_random_walk <- function(ggi_src, ggi_dest, receptor_name, tf_names, n_walks = 10000L, max_hop = 10L, seed = 123L) {
    .Call('_SpaTalk_cpp_random_walk', PACKAGE = 'SpaTalk', ggi_src, ggi_dest, receptor_name, tf_names, n_walks, max_hop, seed)
}

#' Fast cell sampling with early stopping
#' @param spot_ndata Spot expression vector
#' @param sc_ndata_mat SC expression matrix
#' @param cell_indices_by_type List of cell indices for each celltype
#' @param spot_celltypes Cell types needed for this spot
#' @param iter_num Maximum iterations
#' @param tolerance Convergence tolerance
#' @param seed Random seed
#' @return Best cell combination
#' @export
cpp_fast_sampling <- function(spot_ndata, sc_ndata_mat, cell_indices_by_type, spot_celltypes, iter_num = 200L, tolerance = 0.001, seed = 123L) {
    .Call('_SpaTalk_cpp_fast_sampling', PACKAGE = 'SpaTalk', spot_ndata, sc_ndata_mat, cell_indices_by_type, spot_celltypes, iter_num, tolerance, seed)
}

#' Batch co-expression for gene-gene interactions
#' @param st_data_mat Expression matrix
#' @param src_genes Source gene indices (1-based)
#' @param dest_genes Dest gene indices (1-based)
#' @param cell_indices Cell indices to use (1-based)
#' @return Co-expression ratios
#' @export
cpp_batch_coexp <- function(st_data_mat, src_genes, dest_genes, cell_indices) {
    .Call('_SpaTalk_cpp_batch_coexp', PACKAGE = 'SpaTalk', st_data_mat, src_genes, dest_genes, cell_indices)
}

#' Fast Euclidean distance matrix
#' @param x X coordinates
#' @param y Y coordinates
#' @return Distance matrix
#' @export
cpp_fast_dist <- function(x, y) {
    .Call('_SpaTalk_cpp_fast_dist', PACKAGE = 'SpaTalk', x, y)
}

#' Fast K-nearest neighbors
#' @param dist_mat Distance matrix
#' @param query_idx Query cell index (0-based)
#' @param k Number of neighbors
#' @return Neighbor indices (0-based)
#' @export
cpp_knn <- function(dist_mat, query_idx, k) {
    .Call('_SpaTalk_cpp_knn', PACKAGE = 'SpaTalk', dist_mat, query_idx, k)
}

#' Fast batch correlation
#' @param vec1 First vector
#' @param mat Matrix where each column is a vector to correlate with vec1
#' @return Correlations
#' @export
cpp_batch_cor <- function(vec1, mat) {
    .Call('_SpaTalk_cpp_batch_cor', PACKAGE = 'SpaTalk', vec1, mat)
}

